///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SwissTransport
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchForStation recording.
    /// </summary>
    [TestModule("d37c670f-8596-4469-8289-36798d7baccc", ModuleType.Recording, 1)]
    public partial class SearchForStation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SwissTransportRepository repository.
        /// </summary>
        public static SwissTransportRepository repo = SwissTransportRepository.Instance;

        static SearchForStation instance = new SearchForStation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchForStation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchForStation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationText' at 43;5.", repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationTextInfo, new RecordItemIndex(0));
            repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationText.Click("43;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}L{RShiftKey up}uze' with focus on 'MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationText'.", repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationTextInfo, new RecordItemIndex(1));
            repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationText.PressKeys("{RShiftKey down}L{RShiftKey up}uze");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationDropDown' at 5;6.", repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationDropDownInfo, new RecordItemIndex(2));
            repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationDropDown.Click("5;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.lstComboboxItemDepartureStation' at 40;4.", repo.List1000.lstComboboxItemDepartureStationInfo, new RecordItemIndex(3));
            repo.List1000.lstComboboxItemDepartureStation.Click("40;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Luzern, Wey') on item 'MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationText'.", repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationTextInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.MainFormSwissTransport.cmbTripDepartureStation.cmbTripDepartureStationTextInfo, "Text", "Luzern, Wey");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
