///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SwissTransport
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SwissTransportRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("624ba46b-b64c-435b-ad97-90fb77091fbb")]
    public partial class SwissTransportRepository : RepoGenBaseFolder
    {
        static SwissTransportRepository instance = new SwissTransportRepository();
        SwissTransportRepositoryFolders.MainFormSwissTransportAppFolder _mainformswisstransport;
        SwissTransportRepositoryFolders.List1000AppFolder _list1000;
        SwissTransportRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the SwissTransportRepository element repository.
        /// </summary>
        [RepositoryFolder("624ba46b-b64c-435b-ad97-90fb77091fbb")]
        public static SwissTransportRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SwissTransportRepository() 
            : base("SwissTransportRepository", "/", null, 0, false, "624ba46b-b64c-435b-ad97-90fb77091fbb", ".\\RepositoryImages\\SwissTransportRepository624ba46b.rximgres")
        {
            _mainformswisstransport = new SwissTransportRepositoryFolders.MainFormSwissTransportAppFolder(this);
            _list1000 = new SwissTransportRepositoryFolders.List1000AppFolder(this);
            _explorer = new SwissTransportRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("624ba46b-b64c-435b-ad97-90fb77091fbb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainFormSwissTransport folder.
        /// </summary>
        [RepositoryFolder("1aabf49d-5f04-426d-8b49-2d9fe6ee45c0")]
        public virtual SwissTransportRepositoryFolders.MainFormSwissTransportAppFolder MainFormSwissTransport
        {
            get { return _mainformswisstransport; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("2beba9fc-30b8-48fd-a3d6-f03001324b74")]
        public virtual SwissTransportRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("b63f20e4-198d-4fd5-8085-d5c81301eb0e")]
        public virtual SwissTransportRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SwissTransportRepositoryFolders
    {
        /// <summary>
        /// The MainFormSwissTransportAppFolder folder.
        /// </summary>
        [RepositoryFolder("1aabf49d-5f04-426d-8b49-2d9fe6ee45c0")]
        public partial class MainFormSwissTransportAppFolder : RepoGenBaseFolder
        {
            SwissTransportRepositoryFolders.TabTripPageFolder _tabtrippage;
            SwissTransportRepositoryFolders.CmbTripArrivalStationFolder _cmbtriparrivalstation;
            SwissTransportRepositoryFolders.CmbTripDepartureStationFolder _cmbtripdeparturestation;

            /// <summary>
            /// Creates a new MainFormSwissTransport  folder.
            /// </summary>
            public MainFormSwissTransportAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainFormSwissTransport", "/form[@controlname='mainFormSwissTransport']", parentFolder, 30000, null, true, "1aabf49d-5f04-426d-8b49-2d9fe6ee45c0", "")
            {
                _tabtrippage = new SwissTransportRepositoryFolders.TabTripPageFolder(this);
                _cmbtriparrivalstation = new SwissTransportRepositoryFolders.CmbTripArrivalStationFolder(this);
                _cmbtripdeparturestation = new SwissTransportRepositoryFolders.CmbTripDepartureStationFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1aabf49d-5f04-426d-8b49-2d9fe6ee45c0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1aabf49d-5f04-426d-8b49-2d9fe6ee45c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabTripPage folder.
            /// </summary>
            [RepositoryFolder("fc6b35bc-b04e-4dc9-b0af-0eb739acf6a0")]
            public virtual SwissTransportRepositoryFolders.TabTripPageFolder TabTripPage
            {
                get { return _tabtrippage; }
            }

            /// <summary>
            /// The cmbTripArrivalStation folder.
            /// </summary>
            [RepositoryFolder("6fb1f547-08e0-4efd-9f76-a91e98273667")]
            public virtual SwissTransportRepositoryFolders.CmbTripArrivalStationFolder cmbTripArrivalStation
            {
                get { return _cmbtriparrivalstation; }
            }

            /// <summary>
            /// The cmbTripDepartureStation folder.
            /// </summary>
            [RepositoryFolder("da4a87ce-52da-458f-af54-192414328955")]
            public virtual SwissTransportRepositoryFolders.CmbTripDepartureStationFolder cmbTripDepartureStation
            {
                get { return _cmbtripdeparturestation; }
            }
        }

        /// <summary>
        /// The TabTripPageFolder folder.
        /// </summary>
        [RepositoryFolder("fc6b35bc-b04e-4dc9-b0af-0eb739acf6a0")]
        public partial class TabTripPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dtptriptimepickerInfo;
            RepoItemInfo _dtptripdatepickerInfo;
            RepoItemInfo _gdvlastcellInfo;
            RepoItemInfo _btntripsearchInfo;

            /// <summary>
            /// Creates a new TabTripPage  folder.
            /// </summary>
            public TabTripPageFolder(RepoGenBaseFolder parentFolder) :
                    base("TabTripPage", "?/?/tabpage[@controlname='tabTripPage']", parentFolder, 30000, null, false, "fc6b35bc-b04e-4dc9-b0af-0eb739acf6a0", "")
            {
                _dtptriptimepickerInfo = new RepoItemInfo(this, "dtpTripTimePicker", "datetime[@controlname='dtpTripTimePicker']/?/list[]", 30000, null, "b63af62a-123c-452e-ab46-21379247b28f");
                _dtptripdatepickerInfo = new RepoItemInfo(this, "dtpTripDatePicker", "datetime[@controlname='dtpTripDatePicker']/?/list[]", 30000, null, "03ecd784-a32f-4072-b8cc-9261c0347c60");
                _gdvlastcellInfo = new RepoItemInfo(this, "gdvLastCell", "table[@controlname='dgvTripShowFoundTrips']/?/?/cell[@accessiblename='Abfahrt Row 5']", 30000, null, "e13b06d5-f5db-4387-b61f-6f1b7bd0ba28");
                _btntripsearchInfo = new RepoItemInfo(this, "btnTripSearch", "button[@controlname='btnTripSearch']", 30000, null, "3317adfa-1d06-4044-9850-69673a0451e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc6b35bc-b04e-4dc9-b0af-0eb739acf6a0")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc6b35bc-b04e-4dc9-b0af-0eb739acf6a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The dtpTripTimePicker item.
            /// </summary>
            [RepositoryItem("b63af62a-123c-452e-ab46-21379247b28f")]
            public virtual Ranorex.List dtpTripTimePicker
            {
                get
                {
                    return _dtptriptimepickerInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The dtpTripTimePicker item info.
            /// </summary>
            [RepositoryItemInfo("b63af62a-123c-452e-ab46-21379247b28f")]
            public virtual RepoItemInfo dtpTripTimePickerInfo
            {
                get
                {
                    return _dtptriptimepickerInfo;
                }
            }

            /// <summary>
            /// The dtpTripDatePicker item.
            /// </summary>
            [RepositoryItem("03ecd784-a32f-4072-b8cc-9261c0347c60")]
            public virtual Ranorex.List dtpTripDatePicker
            {
                get
                {
                    return _dtptripdatepickerInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The dtpTripDatePicker item info.
            /// </summary>
            [RepositoryItemInfo("03ecd784-a32f-4072-b8cc-9261c0347c60")]
            public virtual RepoItemInfo dtpTripDatePickerInfo
            {
                get
                {
                    return _dtptripdatepickerInfo;
                }
            }

            /// <summary>
            /// The gdvLastCell item.
            /// </summary>
            [RepositoryItem("e13b06d5-f5db-4387-b61f-6f1b7bd0ba28")]
            public virtual Ranorex.Cell gdvLastCell
            {
                get
                {
                    return _gdvlastcellInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The gdvLastCell item info.
            /// </summary>
            [RepositoryItemInfo("e13b06d5-f5db-4387-b61f-6f1b7bd0ba28")]
            public virtual RepoItemInfo gdvLastCellInfo
            {
                get
                {
                    return _gdvlastcellInfo;
                }
            }

            /// <summary>
            /// The btnTripSearch item.
            /// </summary>
            [RepositoryItem("3317adfa-1d06-4044-9850-69673a0451e5")]
            public virtual Ranorex.Button btnTripSearch
            {
                get
                {
                    return _btntripsearchInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnTripSearch item info.
            /// </summary>
            [RepositoryItemInfo("3317adfa-1d06-4044-9850-69673a0451e5")]
            public virtual RepoItemInfo btnTripSearchInfo
            {
                get
                {
                    return _btntripsearchInfo;
                }
            }
        }

        /// <summary>
        /// The CmbTripArrivalStationFolder folder.
        /// </summary>
        [RepositoryFolder("6fb1f547-08e0-4efd-9f76-a91e98273667")]
        public partial class CmbTripArrivalStationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cmbtriparrivalstationtextInfo;
            RepoItemInfo _cmbtriparrivalstationdropdownInfo;

            /// <summary>
            /// Creates a new cmbTripArrivalStation  folder.
            /// </summary>
            public CmbTripArrivalStationFolder(RepoGenBaseFolder parentFolder) :
                    base("cmbTripArrivalStation", ".//combobox[@controlname='cmbTripArrivalStation']", parentFolder, 30000, null, false, "6fb1f547-08e0-4efd-9f76-a91e98273667", "")
            {
                _cmbtriparrivalstationtextInfo = new RepoItemInfo(this, "cmbTripArrivalStationText", "text[@controlid='1001']", 30000, null, "51c5a913-7d16-4cca-bd3c-bd12e7b85bb3");
                _cmbtriparrivalstationdropdownInfo = new RepoItemInfo(this, "cmbTripArrivalStationDropDown", "button[@accessiblename='Open']", 30000, null, "82d481d5-6e59-4e63-abe1-bda17aa336db");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6fb1f547-08e0-4efd-9f76-a91e98273667")]
            public virtual Ranorex.ComboBox Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6fb1f547-08e0-4efd-9f76-a91e98273667")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cmbTripArrivalStationText item.
            /// </summary>
            [RepositoryItem("51c5a913-7d16-4cca-bd3c-bd12e7b85bb3")]
            public virtual Ranorex.Text cmbTripArrivalStationText
            {
                get
                {
                    return _cmbtriparrivalstationtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The cmbTripArrivalStationText item info.
            /// </summary>
            [RepositoryItemInfo("51c5a913-7d16-4cca-bd3c-bd12e7b85bb3")]
            public virtual RepoItemInfo cmbTripArrivalStationTextInfo
            {
                get
                {
                    return _cmbtriparrivalstationtextInfo;
                }
            }

            /// <summary>
            /// The cmbTripArrivalStationDropDown item.
            /// </summary>
            [RepositoryItem("82d481d5-6e59-4e63-abe1-bda17aa336db")]
            public virtual Ranorex.Button cmbTripArrivalStationDropDown
            {
                get
                {
                    return _cmbtriparrivalstationdropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The cmbTripArrivalStationDropDown item info.
            /// </summary>
            [RepositoryItemInfo("82d481d5-6e59-4e63-abe1-bda17aa336db")]
            public virtual RepoItemInfo cmbTripArrivalStationDropDownInfo
            {
                get
                {
                    return _cmbtriparrivalstationdropdownInfo;
                }
            }
        }

        /// <summary>
        /// The CmbTripDepartureStationFolder folder.
        /// </summary>
        [RepositoryFolder("da4a87ce-52da-458f-af54-192414328955")]
        public partial class CmbTripDepartureStationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cmbtripdeparturestationdropdownInfo;
            RepoItemInfo _cmbtripdeparturestationtextInfo;

            /// <summary>
            /// Creates a new cmbTripDepartureStation  folder.
            /// </summary>
            public CmbTripDepartureStationFolder(RepoGenBaseFolder parentFolder) :
                    base("cmbTripDepartureStation", ".//combobox[@controlname='cmbTripDepartureStation']", parentFolder, 30000, null, false, "da4a87ce-52da-458f-af54-192414328955", "")
            {
                _cmbtripdeparturestationdropdownInfo = new RepoItemInfo(this, "cmbTripDepartureStationDropDown", "button[@accessiblename='Open']", 30000, null, "5eefd02c-2a07-4bde-b3d0-6911b1d4dcac");
                _cmbtripdeparturestationtextInfo = new RepoItemInfo(this, "cmbTripDepartureStationText", "text[@controlid='1001']", 30000, null, "495340aa-bce1-43bf-8a9b-b0d35d1387b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da4a87ce-52da-458f-af54-192414328955")]
            public virtual Ranorex.ComboBox Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da4a87ce-52da-458f-af54-192414328955")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cmbTripDepartureStationDropDown item.
            /// </summary>
            [RepositoryItem("5eefd02c-2a07-4bde-b3d0-6911b1d4dcac")]
            public virtual Ranorex.Button cmbTripDepartureStationDropDown
            {
                get
                {
                    return _cmbtripdeparturestationdropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The cmbTripDepartureStationDropDown item info.
            /// </summary>
            [RepositoryItemInfo("5eefd02c-2a07-4bde-b3d0-6911b1d4dcac")]
            public virtual RepoItemInfo cmbTripDepartureStationDropDownInfo
            {
                get
                {
                    return _cmbtripdeparturestationdropdownInfo;
                }
            }

            /// <summary>
            /// The cmbTripDepartureStationText item.
            /// </summary>
            [RepositoryItem("495340aa-bce1-43bf-8a9b-b0d35d1387b8")]
            public virtual Ranorex.Text cmbTripDepartureStationText
            {
                get
                {
                    return _cmbtripdeparturestationtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The cmbTripDepartureStationText item info.
            /// </summary>
            [RepositoryItemInfo("495340aa-bce1-43bf-8a9b-b0d35d1387b8")]
            public virtual RepoItemInfo cmbTripDepartureStationTextInfo
            {
                get
                {
                    return _cmbtripdeparturestationtextInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("2beba9fc-30b8-48fd-a3d6-f03001324b74")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstcomboboxitemdeparturestationInfo;
            RepoItemInfo _lstcomboboxitemarrivalstationInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "2beba9fc-30b8-48fd-a3d6-f03001324b74", "")
            {
                _lstcomboboxitemdeparturestationInfo = new RepoItemInfo(this, "lstComboboxItemDepartureStation", "listitem[@text='Luzern, Wey']", 30000, null, "76776d39-a357-4397-b511-4866a0b425b9");
                _lstcomboboxitemarrivalstationInfo = new RepoItemInfo(this, "lstComboboxItemArrivalStation", "listitem[@text='Luzern, Maihof']", 30000, null, "b4cd04a2-4cfd-4950-9d15-930af292b5f5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2beba9fc-30b8-48fd-a3d6-f03001324b74")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2beba9fc-30b8-48fd-a3d6-f03001324b74")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lstComboboxItemDepartureStation item.
            /// </summary>
            [RepositoryItem("76776d39-a357-4397-b511-4866a0b425b9")]
            public virtual Ranorex.ListItem lstComboboxItemDepartureStation
            {
                get
                {
                    return _lstcomboboxitemdeparturestationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The lstComboboxItemDepartureStation item info.
            /// </summary>
            [RepositoryItemInfo("76776d39-a357-4397-b511-4866a0b425b9")]
            public virtual RepoItemInfo lstComboboxItemDepartureStationInfo
            {
                get
                {
                    return _lstcomboboxitemdeparturestationInfo;
                }
            }

            /// <summary>
            /// The lstComboboxItemArrivalStation item.
            /// </summary>
            [RepositoryItem("b4cd04a2-4cfd-4950-9d15-930af292b5f5")]
            public virtual Ranorex.ListItem lstComboboxItemArrivalStation
            {
                get
                {
                    return _lstcomboboxitemarrivalstationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The lstComboboxItemArrivalStation item info.
            /// </summary>
            [RepositoryItemInfo("b4cd04a2-4cfd-4950-9d15-930af292b5f5")]
            public virtual RepoItemInfo lstComboboxItemArrivalStationInfo
            {
                get
                {
                    return _lstcomboboxitemarrivalstationInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("b63f20e4-198d-4fd5-8085-d5c81301eb0e")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "b63f20e4-198d-4fd5-8085-d5c81301eb0e", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "b5db614c-3f49-4311-9219-95738c47e1ad");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b63f20e4-198d-4fd5-8085-d5c81301eb0e")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b63f20e4-198d-4fd5-8085-d5c81301eb0e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("b5db614c-3f49-4311-9219-95738c47e1ad")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("b5db614c-3f49-4311-9219-95738c47e1ad")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}